---
- hosts: servera.lab.example.com
  remote_user: devops
  become: true
  vars:
    iso_uri: "http://ct.mirror.garr.it/mirrors/CentOS/7/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso"
  tasks:
    - name: Get CentOS minimal ISO
      get_url:
        url: "{{ iso_uri }}"
        dest:  /tmp
        owner: root
        group: root
        mode: 0644
      async: 1
      poll: 0
      register: iso_download
    
    - name: Check if download has finished
      async_status:
        jid: "{{ iso_download.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 20
