---
- hosts: webservers
  remote_user: devops
  become: true
  serial: 1
  tasks:
    - name: Disable {{ inventory_hostname }} web server in the app lb pool
      haproxy:
        state: disabled
        host: "{{ inventory_hostname }}"
        backend: app
        socket: /var/lib/haproxy/stats
        wait: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lbserver'] }}"

    - name: Deploy new version of index.html
      template:
        src: index-ver1.html.j2
        dest: /var/www/html/index.html
      register: pageupgrade

    - name: Reboot {{ inventory_hostname }}
      shell: shutdown -r now "Maintenance reboot"
      async: 1
      poll: 0
      ignore_errors: true
      when: pageupgrade.changed

    - name: Wait for reboot completion
      become: false
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 25
        timeout: 200
      delegate_to: localhost
      when: pageupgrade.changed

    - name: Wait for httpd service to come up
      wait_for:
        port: 80
        host: "{{ inventory_hostname }}"
        timeout: 20

    - name: Enable {{ inventory_hostname }} web server in the app lb pool
      haproxy:
        state: enabled
        host: "{{ inventory_hostname }}"
        backend: app
        socket: /var/lib/haproxy/stats
        wait: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lbserver'] }}"
