---
- hosts: localhost
  gather_facts: false
  vars:
    tower_host: tower.lab.example.com
    tower_user: admin
    tower_password: redhat
  tasks:
    - name: Ping the service
      uri:
        url: "https://{{ tower_host }}/api/v2/ping/"
        return_content: true
        validate_certs: false
        status_code: [200, 201]
      register: ping_status
    - name: Print results
      debug:
        var: ping_status.json

