---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Set a fact
      set_fact:
        employees: "{{ lookup('url', 'http://dummy.restapiexample.com/api/v1/employees') | from_json }}"
      tags: always

    - name: Initialize high_salaries fact as emtpy list
      set_fact:
        high_salaries: []
      tags: always

    - name: Load data into high_salaries fact
      set_fact:
        high_salaries: "{{ high_salaries + [item] }}"
      loop: "{{ employees }}"
      when: item.employee_salary | int > 50000
      tags: always
   
    # Use tags for performance comparisons.
    # Module blockinfile is faster
    - name: Write results using blockinfile
      blockinfile: 
        block: "{{ high_salaries | to_nice_yaml }}"
        path: /tmp/high_salaries.yml
        create: true
        marker: ""
      tags: blockinfile
    
    # Module copy is slower
    - name: Write results using copy
      copy:
        content: "{{ high_salaries | to_nice_yaml }}"
        dest: /tmp/high_salaries.yml
      tags: copy
