---
- hosts: 127.0.0.1
  vars:
    role_name: smtp_glx.yml

  tasks:

    - name: Create roles directory
      file:
        path: roles
        state: directory
        mode: 0755

    - name: Install role
      command: "ansible-galaxy install -r {{ role_name }} -p roles"

      
